In [167]:
import tensorflow as tf
import pandas as pd
import sklearn as sk
import numpy as np
df = pd.read_excel('dataset1.xlsx')
df.head()

crr_Nom  psu_Nem  psu_Leng  psu_Mate  psu_Cie  \
0   INGENIERIA CIVIL INDUSTRIAL      783       653       685      672   
1    INGENIERIA CIVIL BIOMEDICA      799       705       713      686   
2      INGENIERIA CIVIL QUIMICA      688       543       612      534   
3    INGENIERIA CIVIL ELECTRICA      605       598       658      601   
4  INGENIERIA CIVIL INFORMATICA      603       710       668      651   

   psu_Pond  Longitud    Latitud  cred_apr  distancia  F  M  \
0       735 -73.16487 -36.978759        38  20.201244  1  0   
1       756 -73.16487 -36.978759        36  20.201244  1  0   
2       638 -73.16487 -36.978759        36  20.201244  1  0   
3       633 -73.16487 -36.978759        21  20.201244  0  1   
4       657 -73.16487 -36.978759        19  20.201244  0  1   

   PARTICULAR_SUBVENCIONADO  PARTICULAR_PAGADO  MUNICIPAL cluster  
0                         1                  0          0      C2  
1                         1                  0          0      C1  
2                         1                  0          0      C3  
3                         1                  0          0      C2  
4                         1                  0          0      C2

In [168]:
df.crr_Nom.unique()
len(df.crr_Nom.unique())

14

In [169]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
crr_LabelEncoder = preprocessing.LabelEncoder()
crr_LabelEncoder.fit(df.crr_Nom)



LabelEncoder()

In [170]:
list(crr_LabelEncoder.classes_)

['INGENIERIA CIVIL',
 'INGENIERIA CIVIL - PLAN COMUN',
 'INGENIERIA CIVIL AEROESPACIAL',
 'INGENIERIA CIVIL BIOMEDICA',
 'INGENIERIA CIVIL DE MATERIALES',
 'INGENIERIA CIVIL ELECTRICA',
 'INGENIERIA CIVIL ELECTRONICA',
 'INGENIERIA CIVIL EN TELECOMUNICACIONES',
 'INGENIERIA CIVIL INDUSTRIAL',
 'INGENIERIA CIVIL INFORMATICA',
 'INGENIERIA CIVIL MECANICA',
 'INGENIERIA CIVIL METALURGICA',
 'INGENIERIA CIVIL QUIMICA',
 'INGENIERÍA CIVIL DE MINAS']

In [171]:
crr_Nom_numeros=crr_LabelEncoder.transform(df.crr_Nom)
print(crr_Nom_numeros)

[ 8  3 12 ...  5  1  1]


In [172]:
crr_OneHotEncoder = OneHotEncoder(handle_unknown='error')
crr_OneHotEncoder.fit(np.array([crr_Nom_numeros]).T)
crr_Nom_binarios=crr_OneHotEncoder.transform(np.array([crr_Nom_numeros]).T).toarray()
print(crr_Nom_binarios)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [173]:
crr_Nom_binarios[0:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [174]:
columnas_nuevas = ["Carrera " + carrera for carrera in df.crr_Nom.unique()]

In [175]:
columnas_nuevas

['Carrera INGENIERIA CIVIL INDUSTRIAL',
 'Carrera INGENIERIA CIVIL BIOMEDICA',
 'Carrera INGENIERIA CIVIL QUIMICA',
 'Carrera INGENIERIA CIVIL ELECTRICA',
 'Carrera INGENIERIA CIVIL INFORMATICA',
 'Carrera INGENIERIA CIVIL - PLAN COMUN',
 'Carrera INGENIERIA CIVIL METALURGICA',
 'Carrera INGENIERIA CIVIL EN TELECOMUNICACIONES',
 'Carrera INGENIERIA CIVIL MECANICA',
 'Carrera INGENIERÍA CIVIL DE MINAS',
 'Carrera INGENIERIA CIVIL DE MATERIALES',
 'Carrera INGENIERIA CIVIL ELECTRONICA',
 'Carrera INGENIERIA CIVIL',
 'Carrera INGENIERIA CIVIL AEROESPACIAL']

In [176]:
i=0
for columna in columnas_nuevas:
    df[columna] = crr_Nom_binarios[:,i]
    i+=1

In [177]:
df=df.drop("crr_Nom",axis=1)
df

psu_Nem  psu_Leng  psu_Mate  psu_Cie  psu_Pond  Longitud    Latitud  \
0         783       653       685      672       735 -73.16487 -36.978759   
1         799       705       713      686       756 -73.16487 -36.978759   
2         688       543       612      534       638 -73.16487 -36.978759   
3         605       598       658      601       633 -73.16487 -36.978759   
4         603       710       668      651       657 -73.16487 -36.978759   
...       ...       ...       ...      ...       ...       ...        ...   
7861      661       671       633      619       644 -73.01875 -36.786340   
7862      682       681       602      651       641 -73.01875 -36.786340   
7863      641       598       640      633       633 -73.01875 -36.786340   
7864      641       653       595      619       619 -73.01875 -36.786340   
7865      641       524       554      588       576 -73.01875 -36.786340   

      cred_apr  distancia  F  ...  Carrera INGENIERIA CIVIL INFORMATICA  \
0           38  20.201244  1  ...                                   0.0   
1           36  20.201244  1  ...                                   0.0   
2           36  20.201244  1  ...                                   0.0   
3           21  20.201244  0  ...                                   0.0   
4           19  20.201244  0  ...                                   0.0   
...        ...        ... ..  ...                                   ...   
7861         0   4.972717  0  ...                                   0.0   
7862         0   4.972717  1  ...                                   0.0   
7863         0   4.972717  0  ...                                   0.0   
7864         0   4.972717  1  ...                                   0.0   
7865         0   4.972717  1  ...                                   0.0   

      Carrera INGENIERIA CIVIL - PLAN COMUN  \
0                                       0.0   
1                                       0.0   
2                                       0.0   
3                                       1.0   
4                                       0.0   
...                                     ...   
7861                                    0.0   
7862                                    0.0   
7863                                    1.0   
7864                                    0.0   
7865                                    0.0   

      Carrera INGENIERIA CIVIL METALURGICA  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
...                                    ...   
7861                                   0.0   
7862                                   0.0   
7863                                   0.0   
7864                                   0.0   
7865                                   0.0   

      Carrera INGENIERIA CIVIL EN TELECOMUNICACIONES  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   
...                                              ...   
7861                                             0.0   
7862                                             0.0   
7863                                             0.0   
7864                                             0.0   
7865                                             0.0   

     Carrera INGENIERIA CIVIL MECANICA  Carrera INGENIERÍA CIVIL DE MINAS  \
0                                  1.0                                0.0   
1                                  0.0                                0.0   
2                                  0.0                                0.0   
3                                  0.0                                0.0   
4   

In [178]:
list(enumerate(columnas_nuevas))

[(0, 'Carrera INGENIERIA CIVIL INDUSTRIAL'),
 (1, 'Carrera INGENIERIA CIVIL BIOMEDICA'),
 (2, 'Carrera INGENIERIA CIVIL QUIMICA'),
 (3, 'Carrera INGENIERIA CIVIL ELECTRICA'),
 (4, 'Carrera INGENIERIA CIVIL INFORMATICA'),
 (5, 'Carrera INGENIERIA CIVIL - PLAN COMUN'),
 (6, 'Carrera INGENIERIA CIVIL METALURGICA'),
 (7, 'Carrera INGENIERIA CIVIL EN TELECOMUNICACIONES'),
 (8, 'Carrera INGENIERIA CIVIL MECANICA'),
 (9, 'Carrera INGENIERÍA CIVIL DE MINAS'),
 (10, 'Carrera INGENIERIA CIVIL DE MATERIALES'),
 (11, 'Carrera INGENIERIA CIVIL ELECTRONICA'),
 (12, 'Carrera INGENIERIA CIVIL'),
 (13, 'Carrera INGENIERIA CIVIL AEROESPACIAL')]

In [179]:
df["posicion"] = [str(df["Latitud"][i]) + "," + str(df["Longitud"][i]) for i in range(len(df))]
df

psu_Nem  psu_Leng  psu_Mate  psu_Cie  psu_Pond  Longitud    Latitud  \
0         783       653       685      672       735 -73.16487 -36.978759   
1         799       705       713      686       756 -73.16487 -36.978759   
2         688       543       612      534       638 -73.16487 -36.978759   
3         605       598       658      601       633 -73.16487 -36.978759   
4         603       710       668      651       657 -73.16487 -36.978759   
...       ...       ...       ...      ...       ...       ...        ...   
7861      661       671       633      619       644 -73.01875 -36.786340   
7862      682       681       602      651       641 -73.01875 -36.786340   
7863      641       598       640      633       633 -73.01875 -36.786340   
7864      641       653       595      619       619 -73.01875 -36.786340   
7865      641       524       554      588       576 -73.01875 -36.786340   

      cred_apr  distancia  F  ...  Carrera INGENIERIA CIVIL - PLAN COMUN  \
0           38  20.201244  1  ...                                    0.0   
1           36  20.201244  1  ...                                    0.0   
2           36  20.201244  1  ...                                    0.0   
3           21  20.201244  0  ...                                    1.0   
4           19  20.201244  0  ...                                    0.0   
...        ...        ... ..  ...                                    ...   
7861         0   4.972717  0  ...                                    0.0   
7862         0   4.972717  1  ...                                    0.0   
7863         0   4.972717  0  ...                                    1.0   
7864         0   4.972717  1  ...                                    0.0   
7865         0   4.972717  1  ...                                    0.0   

      Carrera INGENIERIA CIVIL METALURGICA  \
0                                      0.0   
1                                      0.0   
2                                      0.0   
3                                      0.0   
4                                      0.0   
...                                    ...   
7861                                   0.0   
7862                                   0.0   
7863                                   0.0   
7864                                   0.0   
7865                                   0.0   

      Carrera INGENIERIA CIVIL EN TELECOMUNICACIONES  \
0                                                0.0   
1                                                0.0   
2                                                0.0   
3                                                0.0   
4                                                0.0   
...                                              ...   
7861                                             0.0   
7862                                             0.0   
7863                                             0.0   
7864                                             0.0   
7865                                             0.0   

      Carrera INGENIERIA CIVIL MECANICA Carrera INGENIERÍA CIVIL DE MINAS  \
0                                   1.0                               0.0   
1                                   0.0                               0.0   
2                                   0.0                               0.0   
3                                   0.0                               0.0   
4                                   0.0                               1.0   
...                                 ...                               ...   
7861                                0.0                               0.0   
7862                                0.0                               0.0   
7863                                0.0                               0.0   
7864                                0.0                               0.0   
7865                                0.0                               0.0   

      Carrera ING

In [180]:
df.posicion.unique()
len(df.posicion.unique())

246

In [181]:
df.distancia.unique()
len(df.distancia.unique())

247

In [182]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(np.array([df.psu_Nem,df.psu_Leng,df.psu_Mate,df.psu_Cie,df.psu_Pond,df.distancia,df.cred_apr]).T)

In [183]:
data_scaled

array([[ 1.60823292,  0.5340369 ,  0.26610913, ...,  1.57088793,
        -0.32816048,  1.38198009],
       [ 1.83322871,  1.32995517,  0.7581588 , ...,  2.00828397,
        -0.32816048,  1.24232355],
       [ 0.27232042, -1.14963638, -1.01673464, ..., -0.44946516,
        -0.32816048,  1.24232355],
       ...,
       [-0.38860471, -0.30779974, -0.52468497, ..., -0.55360707,
        -0.71662371, -1.27149412],
       [-0.38860471,  0.5340369 , -1.31547908, ..., -0.84520443,
        -0.71662371, -1.27149412],
       [-0.38860471, -1.44045268, -2.03598037, ..., -1.74082487,
        -0.71662371, -1.27149412]])

In [184]:
PSU = ["psu_Nem","psu_Leng","psu_Mate","psu_Cie","psu_Pond","distancia","cred_apr"]
columnas_mas_nuevas = ["std " + psu for psu in PSU]

In [185]:
for i, columna in enumerate(columnas_mas_nuevas):
    df[columna] = data_scaled[:,i]

In [186]:
df

psu_Nem  psu_Leng  psu_Mate  psu_Cie  psu_Pond  Longitud    Latitud  \
0         783       653       685      672       735 -73.16487 -36.978759   
1         799       705       713      686       756 -73.16487 -36.978759   
2         688       543       612      534       638 -73.16487 -36.978759   
3         605       598       658      601       633 -73.16487 -36.978759   
4         603       710       668      651       657 -73.16487 -36.978759   
...       ...       ...       ...      ...       ...       ...        ...   
7861      661       671       633      619       644 -73.01875 -36.786340   
7862      682       681       602      651       641 -73.01875 -36.786340   
7863      641       598       640      633       633 -73.01875 -36.786340   
7864      641       653       595      619       619 -73.01875 -36.786340   
7865      641       524       554      588       576 -73.01875 -36.786340   

      cred_apr  distancia  F  ...  Carrera INGENIERIA CIVIL  \
0           38  20.201244  1  ...                       0.0   
1           36  20.201244  1  ...                       0.0   
2           36  20.201244  1  ...                       1.0   
3           21  20.201244  0  ...                       0.0   
4           19  20.201244  0  ...                       0.0   
...        ...        ... ..  ...                       ...   
7861         0   4.972717  0  ...                       0.0   
7862         0   4.972717  1  ...                       0.0   
7863         0   4.972717  0  ...                       0.0   
7864         0   4.972717  1  ...                       0.0   
7865         0   4.972717  1  ...                       0.0   

      Carrera INGENIERIA CIVIL AEROESPACIAL                       posicion  \
0                                       0.0  -36.9787591,-73.1648702999999   
1                                       0.0  -36.9787591,-73.1648702999999   
2                                       0.0  -36.9787591,-73.1648702999999   
3                                       0.0  -36.9787591,-73.1648702999999   
4                                       0.0  -36.9787591,-73.1648702999999   
...                                     ...                            ...   
7861                                    0.0            -36.78634,-73.01875   
7862                                    0.0            -36.78634,-73.01875   
7863                                    0.0            -36.78634,-73.01875   
7864                                    0.0            -36.78634,-73.01875   
7865                                    0.0            -36.78634,-73.01875   

      std psu_Nem std psu_Leng  std psu_Mate  std psu_Cie  std psu_Pond  \
0        1.608233     0.534037      0.266109     0.822509      1.570888   
1        1.833229     1.329955      0.758159     1.055584      2.008284   
2        0.272320    -1.149636     -1.016735    -1.474948     -0.449465   
3       -0.894845    -0.307800     -0.208367    -0.359516     -0.553607   
4       -0.922970     1.406486     -0.032635     0.472896     -0.053726   
...           ...          ...           ...          ...           ...   
7861    -0.107360     0.809547     -0.647697    -0.059848     -0.324495   
7862     0.187947     0.962608     -1.192467     0.472896     -0.386980   
7863    -0.388605    -0.307800     -0.524685     0.173228     -0.553607   
7864    -0.388605     0.534037     -1.315479    -0.059848     -0.845204   
7865    -0.388605    -1.440453     -2.035980    -0.575943     -1.740825   

      std distancia  std cred_apr  
0         -0.328160      1.381980  
1         -0.328160      1.242324  
2         -0.328160      1.242324  
3         -0.328160      0.194900  
4         -0.328160      0.055243  
...             ...           ...  
7861      -0.716624     -1.271494  
7862      -0.716624     -1.271494  
7863      -0.716624     -1.271494  
7864      -0.716624     -1.271494  
7865      -0.716624     -1.271494  

[7866 rows x 37 columns]

In [187]:
borrar = ["posicion","Longitud","Latitud","psu_Nem","psu_Leng","psu_Mate","psu_Cie","psu_Pond","distancia","cred_apr"]
for i in borrar:
    df=df.drop(i,axis=1)

In [188]:
df

F  M  PARTICULAR_SUBVENCIONADO  PARTICULAR_PAGADO  MUNICIPAL cluster  \
0     1  0                         1                  0          0      C2   
1     1  0                         1                  0          0      C1   
2     1  0                         1                  0          0      C3   
3     0  1                         1                  0          0      C2   
4     0  1                         1                  0          0      C2   
...  .. ..                       ...                ...        ...     ...   
7861  0  1                         0                  1          0      C2   
7862  1  0                         0                  1          0      C2   
7863  0  1                         0                  1          0      C3   
7864  1  0                         0                  1          0      C2   
7865  1  0                         0                  1          0      C4   

      Carrera INGENIERIA CIVIL INDUSTRIAL  Carrera INGENIERIA CIVIL BIOMEDICA  \
0                                     0.0                                 0.0   
1                                     0.0                                 0.0   
2                                     0.0                                 0.0   
3                                     0.0                                 0.0   
4                                     0.0                                 0.0   
...                                   ...                                 ...   
7861                                  0.0                                 1.0   
7862                                  0.0                                 1.0   
7863                                  0.0                                 0.0   
7864                                  0.0                                 1.0   
7865                                  0.0                                 1.0   

      Carrera INGENIERIA CIVIL QUIMICA  Carrera INGENIERIA CIVIL ELECTRICA  \
0                                  0.0                                 0.0   
1                                  0.0                                 1.0   
2                                  0.0                                 0.0   
3                                  0.0                                 0.0   
4                                  0.0                                 0.0   
...                                ...                                 ...   
7861                               0.0                                 0.0   
7862                               0.0                                 0.0   
7863                               0.0                                 0.0   
7864                               0.0                                 0.0   
7865                               0.0                                 0.0   

      ...  Carrera INGENIERIA CIVIL ELECTRONICA  Carrera INGENIERIA CIVIL  \
0     ...                                   0.0                       0.0   
1     ...                                   0.0                       0.0   
2     ...                                   0.0                       1.0   
3     ...                                   0.0                       0.0   
4     ...                                   0.0                       0.0   
...   ...                                   ...                       ...   
7861  ...                                   0.0                       0.0   
7862  ...                                   0.0                       0.0   
7863  ...                                   0.0                       0.0   
7864  ...                                   0.0                       0.0   
7865  ...                                   0.0                       0.0   

      Carrera INGENIERIA CIVIL AEROESPACIAL  std psu_Nem  std psu_Leng  \
0                                       0.0     1.608233      0.534037   
1                                       0.0     1.833229      1.329955   
2           

In [189]:
cluster_LabelEncoder = preprocessing.LabelEncoder()
cluster_LabelEncoder.fit(df.cluster)

LabelEncoder()

In [190]:
list(cluster_LabelEncoder.classes_)

['C1', 'C2', 'C3', 'C4']

In [191]:
cluster_numeros=cluster_LabelEncoder.transform(df.cluster)
print(cluster_numeros)

[1 0 2 ... 2 1 3]


In [192]:
cluster_OneHotEncoder = OneHotEncoder(handle_unknown='error')
cluster_OneHotEncoder.fit(np.array([cluster_numeros]).T)
cluster_numeros_binarios=cluster_OneHotEncoder.transform(np.array([cluster_numeros]).T).toarray()
print(cluster_numeros_binarios)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [193]:
df=df.drop("cluster",axis=1)
df

F  M  PARTICULAR_SUBVENCIONADO  PARTICULAR_PAGADO  MUNICIPAL  \
0     1  0                         1                  0          0   
1     1  0                         1                  0          0   
2     1  0                         1                  0          0   
3     0  1                         1                  0          0   
4     0  1                         1                  0          0   
...  .. ..                       ...                ...        ...   
7861  0  1                         0                  1          0   
7862  1  0                         0                  1          0   
7863  0  1                         0                  1          0   
7864  1  0                         0                  1          0   
7865  1  0                         0                  1          0   

      Carrera INGENIERIA CIVIL INDUSTRIAL  Carrera INGENIERIA CIVIL BIOMEDICA  \
0                                     0.0                                 0.0   
1                                     0.0                                 0.0   
2                                     0.0                                 0.0   
3                                     0.0                                 0.0   
4                                     0.0                                 0.0   
...                                   ...                                 ...   
7861                                  0.0                                 1.0   
7862                                  0.0                                 1.0   
7863                                  0.0                                 0.0   
7864                                  0.0                                 1.0   
7865                                  0.0                                 1.0   

      Carrera INGENIERIA CIVIL QUIMICA  Carrera INGENIERIA CIVIL ELECTRICA  \
0                                  0.0                                 0.0   
1                                  0.0                                 1.0   
2                                  0.0                                 0.0   
3                                  0.0                                 0.0   
4                                  0.0                                 0.0   
...                                ...                                 ...   
7861                               0.0                                 0.0   
7862                               0.0                                 0.0   
7863                               0.0                                 0.0   
7864                               0.0                                 0.0   
7865                               0.0                                 0.0   

      Carrera INGENIERIA CIVIL INFORMATICA  ...  \
0                                      0.0  ...   
1                                      0.0  ...   
2                                      0.0  ...   
3                                      0.0  ...   
4                                      0.0  ...   
...                                    ...  ...   
7861                                   0.0  ...   
7862                                   0.0  ...   
7863                                   0.0  ...   
7864                                   0.0  ...   
7865                                   0.0  ...   

      Carrera INGENIERIA CIVIL ELECTRONICA  Carrera INGENIERIA CIVIL  \
0                                      0.0                       0.0   
1                                      0.0                       0.0   
2                                      0.0                       1.0   
3                                      0.0                       0.0   
4                                      0.0                       0.0   
...                                    ...                       ...   
7861                                   0.0                       0.0   
7862                                   0.0                       0

In [195]:
df.to_excel("dataset1_final.xlsx")

PermissionError: [Errno 13] Permission denied: 'dataset1_final.xlsx'

In [196]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.values, cluster_numeros_binarios, test_size=0.20, random_state=42)

In [198]:
y_train

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [200]:
from tensorflow.keras.layers import Input, Dense, Activation,Dropout
from tensorflow.keras.models import Model

In [201]:
input_layer = Input(shape=(df.shape[1],))
dense_layer_1 = Dense(15, activation='relu')(input_layer)
dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)
output = Dense(cluster_numeros_binarios.shape[1], activation='softmax')(dense_layer_2)

model = Model(inputs=input_layer, outputs=output)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [202]:
print(model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 26)]              0         
_________________________________________________________________
dense (Dense)                (None, 15)                405       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                160       
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 44        
Total params: 609
Trainable params: 609
Non-trainable params: 0
_________________________________________________________________
None


In [203]:
history = model.fit(X_train, y_train, batch_size=8, epochs=50, verbose=1, validation_split=0.2)

Train on 5033 samples, validate on 1259 samples
Epoch 1/50
5033/5033 [==============================] - 3s 600us/sample - loss: 0.7579 - acc: 0.7016 - val_loss: 0.5038 - val_acc: 0.7903
Epoch 2/50
5033/5033 [==============================] - 2s 336us/sample - loss: 0.4565 - acc: 0.8087 - val_loss: 0.4440 - val_acc: 0.8046
Epoch 3/50
5033/5033 [==============================] - 2s 363us/sample - loss: 0.4188 - acc: 0.8216 - val_loss: 0.4205 - val_acc: 0.8070
Epoch 4/50
5033/5033 [==============================] - 2s 355us/sample - loss: 0.3992 - acc: 0.8319 - val_loss: 0.4046 - val_acc: 0.8205
Epoch 5/50
5033/5033 [==============================] - 2s 360us/sample - loss: 0.3853 - acc: 0.8399 - val_loss: 0.3983 - val_acc: 0.8221
Epoch 6/50
5033/5033 [==============================] - 2s 334us/sample - loss: 0.3741 - acc: 0.8424 - val_loss: 0.3957 - val_acc: 0.8189
Epoch 7/50
5033/5033 [==============================] - 2s 342us/sample - loss: 0.3655 - acc: 0.8446 - val_loss: 0.3865 - va

In [204]:
score = model.evaluate(X_test, y_test, verbose=1)

print("Test Score:", score[0])
print("Test Accuracy:", score[1])

1574/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

Test Score: 0.3307577243223881
Test Accuracy: 0.86086404
