<a href="https://colab.research.google.com/github/tomasturbo/MLBI/blob/master/Ejercicio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
files.upload()

Saving dataset1.xlsx to dataset1.xlsx


{'dataset1.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00b\xee\x9dh^\x01\x00\x00\x90\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\

In [0]:
import tensorflow as tf
import pandas as pd
import sklearn as sk
import numpy as np
df = pd.read_excel('dataset1.xlsx')
df.head()

crr_Nom  psu_Nem  ...  MUNICIPAL  cluster
0   INGENIERIA CIVIL INDUSTRIAL      783  ...          0       C2
1    INGENIERIA CIVIL BIOMEDICA      799  ...          0       C1
2      INGENIERIA CIVIL QUIMICA      688  ...          0       C3
3    INGENIERIA CIVIL ELECTRICA      605  ...          0       C2
4  INGENIERIA CIVIL INFORMATICA      603  ...          0       C2

[5 rows x 16 columns]

In [0]:
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder
crr_LabelEncoder = preprocessing.LabelEncoder()
crr_LabelEncoder.fit(df.crr_Nom)



LabelEncoder()

In [0]:
crr_Nom_numeros=crr_LabelEncoder.transform(df.crr_Nom)
print(crr_Nom_numeros)

[ 8  3 12 ...  5  1  1]


In [0]:
crr_OneHotEncoder = OneHotEncoder(handle_unknown='error')
crr_OneHotEncoder.fit(np.array([crr_Nom_numeros]).T)
crr_Nom_binarios=crr_OneHotEncoder.transform(np.array([crr_Nom_numeros]).T).toarray()
print(crr_Nom_binarios)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [0]:
crr_Nom_binarios[0:10]

array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [0]:
columnas_nuevas = ["Carrera " + carrera for carrera in df.crr_Nom.unique()]

In [0]:
columnas_nuevas

['Carrera INGENIERIA CIVIL INDUSTRIAL',
 'Carrera INGENIERIA CIVIL BIOMEDICA',
 'Carrera INGENIERIA CIVIL QUIMICA',
 'Carrera INGENIERIA CIVIL ELECTRICA',
 'Carrera INGENIERIA CIVIL INFORMATICA',
 'Carrera INGENIERIA CIVIL - PLAN COMUN',
 'Carrera INGENIERIA CIVIL METALURGICA',
 'Carrera INGENIERIA CIVIL EN TELECOMUNICACIONES',
 'Carrera INGENIERIA CIVIL MECANICA',
 'Carrera INGENIERÍA CIVIL DE MINAS',
 'Carrera INGENIERIA CIVIL DE MATERIALES',
 'Carrera INGENIERIA CIVIL ELECTRONICA',
 'Carrera INGENIERIA CIVIL',
 'Carrera INGENIERIA CIVIL AEROESPACIAL']

In [0]:
i=0
for columna in columnas_nuevas:
    df[columna] = crr_Nom_binarios[:,i]
    i+=1

In [0]:
df=df.drop("crr_Nom",axis=1)
df

psu_Nem  ...  Carrera INGENIERIA CIVIL AEROESPACIAL
0         783  ...                                    0.0
1         799  ...                                    0.0
2         688  ...                                    0.0
3         605  ...                                    0.0
4         603  ...                                    0.0
...       ...  ...                                    ...
7861      661  ...                                    0.0
7862      682  ...                                    0.0
7863      641  ...                                    0.0
7864      641  ...                                    0.0
7865      641  ...                                    0.0

[7866 rows x 29 columns]

In [0]:
df["posicion"] = [str(df["Latitud"][i]) + "," + str(df["Longitud"][i]) for i in range(len(df))]
df

psu_Nem  ...                       posicion
0         783  ...  -36.9787591,-73.1648702999999
1         799  ...  -36.9787591,-73.1648702999999
2         688  ...  -36.9787591,-73.1648702999999
3         605  ...  -36.9787591,-73.1648702999999
4         603  ...  -36.9787591,-73.1648702999999
...       ...  ...                            ...
7861      661  ...            -36.78634,-73.01875
7862      682  ...            -36.78634,-73.01875
7863      641  ...            -36.78634,-73.01875
7864      641  ...            -36.78634,-73.01875
7865      641  ...            -36.78634,-73.01875

[7866 rows x 30 columns]

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 
data_scaled = scaler.fit_transform(np.array([df.psu_Nem,df.psu_Leng,df.psu_Mate,df.psu_Cie,df.psu_Pond,df.distancia,df.cred_apr]).T)

In [0]:
data_scaled

array([[ 1.60823292,  0.5340369 ,  0.26610913, ...,  1.57088793,
        -0.32816048,  1.38198009],
       [ 1.83322871,  1.32995517,  0.7581588 , ...,  2.00828397,
        -0.32816048,  1.24232355],
       [ 0.27232042, -1.14963638, -1.01673464, ..., -0.44946516,
        -0.32816048,  1.24232355],
       ...,
       [-0.38860471, -0.30779974, -0.52468497, ..., -0.55360707,
        -0.71662371, -1.27149412],
       [-0.38860471,  0.5340369 , -1.31547908, ..., -0.84520443,
        -0.71662371, -1.27149412],
       [-0.38860471, -1.44045268, -2.03598037, ..., -1.74082487,
        -0.71662371, -1.27149412]])

In [0]:
PSU = ["psu_Nem","psu_Leng","psu_Mate","psu_Cie","psu_Pond","distancia","cred_apr"]
columnas_mas_nuevas = ["std " + psu for psu in PSU]

In [0]:
for i, columna in enumerate(columnas_mas_nuevas):
    df[columna] = data_scaled[:,i]

In [0]:
df

psu_Nem  psu_Leng  psu_Mate  ...  std psu_Pond  std distancia  std cred_apr
0         783       653       685  ...      1.570888      -0.328160      1.381980
1         799       705       713  ...      2.008284      -0.328160      1.242324
2         688       543       612  ...     -0.449465      -0.328160      1.242324
3         605       598       658  ...     -0.553607      -0.328160      0.194900
4         603       710       668  ...     -0.053726      -0.328160      0.055243
...       ...       ...       ...  ...           ...            ...           ...
7861      661       671       633  ...     -0.324495      -0.716624     -1.271494
7862      682       681       602  ...     -0.386980      -0.716624     -1.271494
7863      641       598       640  ...     -0.553607      -0.716624     -1.271494
7864      641       653       595  ...     -0.845204      -0.716624     -1.271494
7865      641       524       554  ...     -1.740825      -0.716624     -1.271494

[7866 rows x 37 columns]

In [0]:
borrar = ["posicion","Longitud","Latitud","psu_Nem","psu_Leng","psu_Mate","psu_Cie","psu_Pond","distancia","cred_apr"]
for i in borrar:
    df=df.drop(i,axis=1)

In [0]:
df

F  M  PARTICULAR_SUBVENCIONADO  ...  std psu_Pond  std distancia std cred_apr
0     1  0                         1  ...      1.570888      -0.328160     1.381980
1     1  0                         1  ...      2.008284      -0.328160     1.242324
2     1  0                         1  ...     -0.449465      -0.328160     1.242324
3     0  1                         1  ...     -0.553607      -0.328160     0.194900
4     0  1                         1  ...     -0.053726      -0.328160     0.055243
...  .. ..                       ...  ...           ...            ...          ...
7861  0  1                         0  ...     -0.324495      -0.716624    -1.271494
7862  1  0                         0  ...     -0.386980      -0.716624    -1.271494
7863  0  1                         0  ...     -0.553607      -0.716624    -1.271494
7864  1  0                         0  ...     -0.845204      -0.716624    -1.271494
7865  1  0                         0  ...     -1.740825      -0.716624    -1.271494

[7866 rows x 27 columns]

In [0]:
cluster_LabelEncoder = preprocessing.LabelEncoder()
cluster_LabelEncoder.fit(df.cluster)

LabelEncoder()

In [0]:
list(cluster_LabelEncoder.classes_)

['C1', 'C2', 'C3', 'C4']

In [0]:
cluster_numeros=cluster_LabelEncoder.transform(df.cluster)
print(cluster_numeros)

[1 0 2 ... 2 1 3]


In [0]:
cluster_OneHotEncoder = OneHotEncoder(handle_unknown='error')
cluster_OneHotEncoder.fit(np.array([cluster_numeros]).T)
cluster_numeros_binarios=cluster_OneHotEncoder.transform(np.array([cluster_numeros]).T).toarray()
print(cluster_numeros_binarios)

[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


In [0]:
df=df.drop("cluster",axis=1)
df

F  M  PARTICULAR_SUBVENCIONADO  ...  std psu_Pond  std distancia  std cred_apr
0     1  0                         1  ...      1.570888      -0.328160      1.381980
1     1  0                         1  ...      2.008284      -0.328160      1.242324
2     1  0                         1  ...     -0.449465      -0.328160      1.242324
3     0  1                         1  ...     -0.553607      -0.328160      0.194900
4     0  1                         1  ...     -0.053726      -0.328160      0.055243
...  .. ..                       ...  ...           ...            ...           ...
7861  0  1                         0  ...     -0.324495      -0.716624     -1.271494
7862  1  0                         0  ...     -0.386980      -0.716624     -1.271494
7863  0  1                         0  ...     -0.553607      -0.716624     -1.271494
7864  1  0                         0  ...     -0.845204      -0.716624     -1.271494
7865  1  0                         0  ...     -1.740825      -0.716624     -1.271494

[7866 rows x 26 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.values, cluster_numeros_binarios, test_size=0.20, random_state=42)

In [0]:
from tensorflow.keras.layers import Input, Dense, Activation,Dropout
from tensorflow.keras.models import Model

In [0]:
input_layer = Input(shape=(df.shape[1],))
dense_layer_1 = Dense(15, activation='relu')(input_layer)
dense_layer_2 = Dense(10, activation='relu')(dense_layer_1)
output = Dense(cluster_numeros_binarios.shape[1], activation='softmax')(dense_layer_2)

model = Model(inputs=input_layer, outputs=output)
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])

In [0]:
print(model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 26)]              0         
_________________________________________________________________
dense (Dense)                (None, 15)                405       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                160       
_________________________________________________________________
dense_2 (Dense)              (None, 4)                 44        
Total params: 609
Trainable params: 609
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
history = model.fit(X_train, y_train, batch_size=8, epochs=50, verbose=1)

Epoch 1/50
787/787 [==============================] - 1s 1ms/step - loss: 0.8168 - acc: 0.6521
Epoch 2/50
787/787 [==============================] - 1s 1ms/step - loss: 0.4935 - acc: 0.7869
Epoch 3/50
787/787 [==============================] - 1s 1ms/step - loss: 0.4434 - acc: 0.8134
Epoch 4/50
787/787 [==============================] - 1s 1ms/step - loss: 0.4207 - acc: 0.8187
Epoch 5/50
787/787 [==============================] - 1s 1ms/step - loss: 0.4030 - acc: 0.8239
Epoch 6/50
787/787 [==============================] - 1s 1ms/step - loss: 0.3906 - acc: 0.8304
Epoch 7/50
787/787 [==============================] - 1s 1ms/step - loss: 0.3779 - acc: 0.8349
Epoch 8/50
787/787 [==============================] - 1s 1ms/step - loss: 0.3673 - acc: 0.8423
Epoch 9/50
787/787 [==============================] - 1s 1ms/step - loss: 0.3591 - acc: 0.8423
Epoch 10/50
787/787 [==============================] - 1s 1ms/step - loss: 0.3490 - acc: 0.8469
Epoch 11/50
787/787 [============================

In [0]:
score = model.evaluate(X_test, y_test, verbose=1)

print("Test Score:", score[0])
print("Test Accuracy:", score[1])

50/50 [==============================] - 0s 955us/step - loss: 0.3389 - acc: 0.8602
Test Score: 0.33887484669685364
Test Accuracy: 0.8602287173271179
